### ISSUE TITLE
Componente sem nome 1#

### ISSUE THREAD

**Issue by micaelmz** [HiveSoft-UEFS/votaai-frontend#32]
# ?? Component

## Descrição

O `` é um componente que exibe um título, uma descrição e um botão de interação personalizável. Esse botão de interação é representado pelo componente `CustomButton`, permitindo a personalização de ações conforme necessário.

<div align="center">
  <img src="https://github.com/HiveSoft-UEFS/votaai-frontend/assets/96327378/5c9baf18-3abb-46f1-b0ab-8ed5979c6526" width="30%">
</div>

## Propriedades (Props)

| Propriedade       | Tipo       | Obrigatório | Descrição                                                  |
|-------------------|------------|-------------|------------------------------------------------------------|
| `title`           | `string`   | Sim         | Título do componente.                                      |
| `description`     | `string`   | Sim         | Descrição do componente.                                   |
| `buttonLabel`     | `string`   | Sim         | Texto exibido no botão de interação.                      |
| `onButtonClick`   | `function` | Sim         | Função a ser executada ao clicar no botão de interação.    |

### Estado Interno

| Propriedade           | Tipo       | Descrição                                                      |
|-----------------------|------------|----------------------------------------------------------------|
| `isButtonDisabled`    | `boolean`  | Indica se o botão de interação está desativado.                |

### Eventos

| Evento         | Descrição                                            |
|----------------|------------------------------------------------------|
| `onClick`      | Evento disparado ao clicar no botão de interação.    |

## Exemplo de Uso
```jsx
import React from 'react';
import Component from './components/component';

const Example = () => {
  return (
    <Component 
        title="Compartilhe Pensamentos"
        description="Seja parte de uma comunidade cada vez maior."
        buttonLabel="CRIAR VOTAÇÃO"
    />
  );
};

export default Example;
```

**Comment by LucasCarneiro3301** [comment]
to tentando atribuir essa tarefa mas não aparece a opção pra mim
